apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: quarkus-monitor
  labels:
    team: backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: quarkus-monitor
      app.kubernetes.io/version: 1.0.0
  endpoints:
  - port: http