---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ansible-eda
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ansible-eda
rules:
  - apiGroups: ["apps"]
    resources: ["pods", "deployments", "services", "jobs", "deployments/scale"]
    verbs: ["list", "get", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ansible-eda
roleRef:
  kind: Role
  name: ansible-eda
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: ansible-eda
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: ansible-eda
    app.kubernetes.io/version: 1.0.0
  name: ansibleeda
spec:
  ports:
    - name: http
      port: 5001
      protocol: TCP
      targetPort: 5001
  selector:
    app.kubernetes.io/name: ansible-eda
    app.kubernetes.io/version: 1.0.0
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/name: ansible-eda
    app.openshift.io/runtime: ansible
  name: ansible-eda
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0
      app.kubernetes.io/name: ansible-eda
  template:
    metadata:
      labels:
        app.kubernetes.io/version: 1.0.0
        app.kubernetes.io/name: ansible-eda
    spec:
      serviceAccountName: ansible-eda
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              value: {{ .Release.Namespace }}
          image: {{ .Values.ansible_eda.image }}
          imagePullPolicy: Always
          name: ansible-eda
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 5001
              name: http
              protocol: TCP
