apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: config-example
  labels:
    alertmanagerConfig: example
spec:
  route:
    groupBy: [...]
    repeatInterval: 1m
    receiver: 'webhook'
  receivers:
  - name: 'webhook'
    webhookConfigs:
    - url: 'http://ansibleeda.{{ .Release.Namespace }}.svc.cluster.local:5001/endpoint'
---
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: example
spec:
  replicas: 1
  alertmanagerConfigSelector:
    matchLabels:
      alertmanagerConfig: example
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-example
spec:
  type: NodePort
  ports:
  - name: web
    # nodePort: 30903
    port: 9093
    protocol: TCP
    targetPort: web
  selector:
    alertmanager: example
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: alertmanager-example
  name: alertmanager-example
spec:
  port:
    targetPort: 9093
  to:
    kind: Service
    name: alertmanager-example
    weight: 100